##
## Deploy the Network policies created in PROD via the OCP project template?
deployProdDefaults: true
##
## Allow cross namespace access for a specific port and app.

crossNamespaceAccess:
  - port: 10042
    toNs:
      app: dx-green-core
    fromNs:
      name: dxb
      app: dx-blue-core
